#!/usr/bin/env bash
APP="behemoth"

# Configuration of where the releases would be built.
BUILD_HOST="62.109.23.250"
BUILD_USER="joker"
BUILD_AT="/home/joker/applications/forelle-io/behemoth/builds"

# The location where built releases are going to be stored.
RELEASE_STORE=joker@62.109.23.250:/home/joker/applications/forelle-io/behemoth/release_store/

# Host and use of where the app would run.
PRODUCTION_HOSTS="62.109.23.250"
PRODUCTION_USER="joker"
DELIVER_TO="/home/joker/applications/forelle-io/behemoth"

AUTO_VERSION=git-branch+git-revision

pre_erlang_get_and_update_deps() {
 # copy it on the build host to the build directory when building
 local _secret_config_file_on_build_host="/home/joker/applications/forelle-io/behemoth/prod.secret.exs"

 status "Linking '$_secret_config_file_on_build_host' to build config dir"
 __sync_remote "
   ln -sfn '$_secret_config_file_on_build_host' '$BUILD_AT/config/prod.secret.exs'
 "
}

pre_erlang_clean_compile() {
 status "Compiling code"
 __sync_remote "
   [ -f ~/.profile ] && source ~/.profile
   set -e
   cd '$BUILD_AT'
   APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD do deps.get, compile
 "

 status "Running phoenix.digest"
 __sync_remote "
   [ -f ~/.profile ] && source ~/.profile
   set -e
   cd '$BUILD_AT'
   APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
 "
}

post_extract_release_archive() {
  status "Refreshing start_erl.data"
  __remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd $DELIVER_TO/$APP
    if [ -f 'var/start_erl.data' ]; then
      cp releases/start_erl.data var/start_erl.data $SILENCE
    fi
  "
}